			<!-- Footer -->
				<div id="footer-wrapper">
					<footer id="footer" class="container">
						<div class="row">
							<div class="3u 6u(medium) 12u$(small)">

								<!-- Links -->
									<section class="widget links">
										<h3>Made at LIF</h3>
										<img src="http://liflab.github.io/beepbeep-3/images/logo-shadow.png" alt="LIF"/><br/>
										BeepBeep was developed through the research done at <a href="http://liflab.ca">LIF</a>, the Formal Computer Science Laboratory in <a href="http://www.uqac.ca/">Université du Québec à Chicoutimi</a>, Canada.
									</section>

							</div>
							<div class="3u 6u$(medium) 12u$(small)">

								<!-- Links -->
									<section class="widget links">
										<h3>Interested?</h3>
										<p>BeepBeep is free software, released under the
										<a href="https://www.gnu.org/copyleft/lesser.html">GNU LGPL</a>.
										This means you can include it as a library in any project,
										including closed-source commercial software.</p>
									</section>

							</div>

							<div class="3u 6u$(medium) 12u$(small)">

								<!-- Contact -->
									<section class="widget contact last">
										<h3>Contact Us</h3>
										<ul>
											<!--<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>-->
											<li><a href="https://www.facebook.com/liflab" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
											<!--<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
											<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
											<li><a href="#" class="icon fa-pinterest"><span class="label">Pinterest</span></a></li>-->
										</ul>
										<p>Université du Québec à Chicoutimi<br />
										Chicoutimi, QC G7H 2B1<br />
										Canada</p>
									</section>

							</div>
						</div>
						<div class="row">
							<div class="12u">
								<div id="copyright">
									<ul class="menu">
										<li>&copy; 2015-2016 Laboratoire d'informatique formelle. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li><li>This site is generated by <a href="http://github.com/sylvainhalle/FantasticWindmill">Fantastic Windmill</a></li>
									</ul>
								</div>
							</div>
						</div>
					</footer>
				</div>

			</div>

		<!-- Scripts -->

			<script src="/assets/js/jquery.min.js"></script>
			<script src="/assets/js/jquery.dropotron.min.js"></script>
			<script src="/assets/js/skel.min.js"></script>
			<script src="/assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="/assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="/assets/js/main.js"></script>
			<?php include ("template_code.php"); ?>

	</body>
</html>
<!-- :indentSize=2:tabSize=2: -->
